- name: 'Deploy gcp vm'
  hosts: localhost
  connection: local
  
  vars:
      service_account_email: ansible@pacific-byte-327001.iam.gserviceaccount.com
      credentials_file: pacific-byte-327001-ed998a6306e0.json
      project_id: "pacific-byte-327001"
      image: projects/centos-cloud/global/images/family/centos-7
      gcp_region: "us-west1"
      gcp_zone: "us-west1-a"
      gcp_cred_kind: "serviceaccount"

  # Roles & Tasks
  tasks:

  - name: create a network
    gcp_compute_network:
         name: 'network-instance'
         project: "{{ project_id }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ credentials_file }}"
         auto_create_subnetworks: true
         state: present
    register: network

  - name: create a address
    gcp_compute_address:
         name: 'address-instance'
         region: "{{ gcp_region }}"
         project: "{{ project_id }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ credentials_file }}"
         state: present
    register: address

  - name: create a instance
    gcp_compute_instance:
      name: vm-instance-1
      project: "{{ project_id }}"
      zone: "{{ gcp_zone }}"
      machine_type: n1-standard-1
      disks:
      - auto_delete: 'true'
        boot: 'true'
        initialize_params:
          disk_size_gb: 300
          source_image: "{{image}}"
      network_interfaces:
        - network: "{{ network }}"
          access_configs:
            - name: 'External NAT'
              nat_ip: "{{ address }}"
              type: 'ONE_TO_ONE_NAT'
      labels:
        environment: testing
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ credentials_file }}"
      state: present
